#!/usr/bin/env bash
# Install Nginx server and redirect /redirect_me permanently

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/sekaycee permanent;/" /etc/nginx/sites-available/default
service nginx start
