#!/usr/bin/env bash
# Automate fix to cause nginx to always listen to port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
