#!/usr/bin/env bash
# Display message indefinitely and read some signals

clean_up='rm /var/run/myscript.pid; exit $?'

echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$clean_up" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$clean_up" SIGQUIT
while true; do
  echo "To infinity and beyond"
done
