#!/usr/bin/env bash
# Display numbers from 1 to 100 in list format:
#   Display "FizzBuzz" when the number is a multiple of 3 and 5
#   Display "Fizz" when the number is a multiple of 3
#   Display "Buzz" when the number is a multiple of 5
#   Otherwise, display the number
for i in {1..100}
do
    if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i % 5)) -eq 0 ]
    then
	echo "Buzz"
    elif [ $((i % 3)) -eq 0 ]
    then
	echo "Fizz"
    else
	echo "$i"
    fi
done
