#!/usr/bin/env bash
# Loop from 1 to 10 and display:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations
i=1
while [ $i -le 10 ]
do
  if [ $i -eq 4 ]
  then
    echo "bad luck"
  elif [ $i -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
