#!/usr/bin/env bash
# Make task #1 short and sweet
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
su nginx -c "service nginx start"
